Feature/15 media upload db update
surfriderfoundationeurope/po-mobile-backend pull request #35
Opened 2021-02-19 10:08 UTC by benzinamohamedelyes

2021-02-19 10:16 UTC, benzinamohamedelyes commented
@cmaneu qu'en pense tu? c'est des demandes faites pour ajouter les remarques et les trajectory points

2021-02-23 21:05 UTC, cmaneu commented
@benzinamohamedelyes Je comprends pas bien de quel branche à quelle branche on va. Tu as un peu de temps demain (Mercredi) pour que l'on s'appelle (entre 12h et 13h30 de préférence)

2021-02-23 21:10 UTC, cmaneu requested changes

2021-02-23 21:10 UTC, cmaneu commented on function/Startup.cs
> +            app.UseCors(options => options.AllowAnyOrigin());
Ca c'est pas bon. On ne doit pas autoriser toutes les origines sur tous les verbes. 
CORS est déjà correctement configuré côté hosting (Azure Functions). 
Si il y a un besoin pour du dev local, alors il faut faire autrement (un flag de config par exemple)

2021-02-23 21:10 UTC, cmaneu commented on function/Startup.cs
> +            services.AddCors(c => c.AddPolicy("AllowOrigin", options => options.AllowAnyOrigin()));
Idem remarque ci-dessus

2021-02-24 09:28 UTC, benzinamohamedelyes commented on function/Startup.cs
> +            services.AddCors(c => c.AddPolicy("AllowOrigin", options => options.AllowAnyOrigin()));
ici aussi

2021-02-24 09:28 UTC, benzinamohamedelyes commented on function/Startup.cs
> +            app.UseCors(options => options.AllowAnyOrigin());
c'est bon j'ai enlevé les lignes concernés

2021-02-24 09:31 UTC, benzinamohamedelyes commented
@cmaneu je suis dispo,


> @cmaneu qu'en pense tu? c'est des demandes faites pour ajouter les remarques et les trajectory points

@cmaneu  je suis toujours dispo, si tu le peux envois moi une invitation

2021-02-26 19:27 UTC, cmaneu commented on function/Service/PostgresqlImageStore.cs
> +                    var query = $"INSERT INTO label.\"images_for_labelling\" (id, id_creator_fk, createdon, filename, view, image_quality, context, container_url) VALUES (@Id, (SELECT id from campaig
On doit changer cela. Il n'y a aucun intérêt à avoir ce select dans cet insert.

2021-03-04 12:19 UTC, benzinamohamedelyes commented on function/Service/PostgresqlImageStore.cs
> +                    var query = $"INSERT INTO label.\"images_for_labelling\" (id, id_creator_fk, createdon, filename, view, image_quality, context, container_url) VALUES (@Id, (SELECT id from campaig
j'ai pas pu insérer directement (foreign key violation )

2021-03-05 13:05 UTC, closed without merging